name: Build & Publish Docker image

on:
  push:
    branches: [ "main", "test/api" ]    
  pull_request:
    branches: [ "main", "test/api" ]    

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
      IMAGE_NAME: docker-openvpn-client

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker registry
      run: echo "${{ secrets.DOCKER_ACCESS_TOKEN }}" | docker login $DOCKER_REGISTRY -u ${{ secrets.DOCKER_ACCESS_USER }} --password-stdin

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref == 'refs/heads/main' && 'latest' || github.ref_name }}-test
