name: Build & Publish Docker image

on:
  push:
    branches: [ "main", "testing" ]    
  pull_request:
    branches: [ "main", "testing" ]    

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
      IMAGE_NAME: docker-openvpn-client

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker registry
      run: echo "${{ secrets.DOCKER_ACCESS_TOKEN }}" | docker login $DOCKER_REGISTRY -u ${{ secrets.DOCKER_ACCESS_USER }} --password-stdin

    - name: Prepare
      id: prep
      run: |
        BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//-/g')
        echo ::set-output name=branch::${BRANCH_NAME}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.prep.outputs.branch }}-test